### PR TITLE
Add platform parameter to action template

### PR DESCRIPTION
**Pull request by benlee0423**
Rename docker image based on the platform.
- awiciroh/ciroh-ngen-image-x86:latest
- awiciroh/ciroh-ngen-image-arm:latest

### CODE REVIEW

**Review by arpita0911patel — COMMENTED** [review]
This looks good, we should go ahead and merge it.

**Review by ZacharyWills — APPROVED** [review]

**Review by ZacharyWills — APPROVED** [review]
Probably need to add the arm workflow to the manual workflow, so if you select to run them manually it creates both arm and x86

**Review by ZacharyWills — APPROVED** [review]

**Comment by arpita0911patel** [comment]
Approving this PR.

**Review by arpita0911patel — APPROVED** [review]
Approved

**Pull request merged**
