### PR TITLE
Version upgrades

### LINKED ISSUE #24: ngen-parallel mode is not working.
## Current behavior
While trying to use "AWI_16_680661_001" data for the model, and selecting parallel run, it's throwing below error: 
"Missing required argument for partition file path."

## Expected behavior
Should create the output files.

## Steps to replicate behavior (include URLs)

apatel54@UA-W2RP43G:~/Desktop/ngen_data|⇒  **docker run --rm -it -v "$(pwd)"/AWI_16_680661_001:/ngen/AWI_001 --platform=linux/amd64 awiciroh/ciroh-ngen-image:latest** 
Working directory is 
/ngen
Found these Catchment files:
/ngen/ngen/data/catchment_data.geojson
/ngen/ngen/data/catchment_data_test1.geojson
/ngen/ngen/extern/cfe/cfe/params/data/hydrofabrics/releases/beta/01a/catchments.geojson
/ngen/ngen/extern/topmodel/topmodel/params/data/hydrofabrics/releases/beta/01a/catchments.geojson
/ngen/AWI_001/config/catchments.geojson
Found these Nexus files:
/ngen/ngen/data/nexus_data.geojson
/ngen/AWI_001/config/nexus.geojson
Found these Realization files:
/ngen/ngen/data/example_bmi_multi_realization_config_w_routing.json
/ngen/ngen/data/example_bmi_multi_realization_config_w_noah_pet_cfe.json
/ngen/ngen/data/example_bmi_multi_realization_config__macos.json
/ngen/ngen/data/test_bmi_multi_realization_config_w_netcdf.json
/ngen/ngen/data/lstm/example_lstm_realization_config.json
/ngen/ngen/data/test_realization_config.json
/ngen/ngen/data/example_realization_config.json
/ngen/ngen/data/test_bmi_multi_realization_config.json
/ngen/ngen/data/example_bmi_multi_realization_config.json
/ngen/ngen/data/example_realization_config_w_bmi_c__lin_mac.json
/ngen/ngen/data/example_bmi_multi_realization_config_w_netcdf.json
/ngen/ngen/data/test_bmi_multi_realization_config_w_noah_pet_cfe.json
/ngen/ngen/extern/sloth/test/data/sloth_cfe_realization.json
/ngen/ngen/extern/sloth/test/data/sloth_realization.json
/ngen/ngen/extern/SoilFreezeThaw/SoilFreezeThaw/configs/realization_config_multi_linux.json
/ngen/ngen/extern/SoilFreezeThaw/SoilFreezeThaw/configs/realization_config_multi_macos.json
/ngen/ngen/extern/SoilFreezeThaw/SoilFreezeThaw/configs/realization_config_standalone_linux.json
/ngen/ngen/extern/SoilFreezeThaw/SoilFreezeThaw/configs/realization_config_standalone_macos.json
/ngen/ngen/extern/SoilMoistureProfiles/SoilMoistureProfiles/config/realization_config_smp_macos.json
/ngen/ngen/extern/SoilMoistureProfiles/SoilMoistureProfiles/config/realization_config_smp_linux.json
/ngen/AWI_001/config/awi_simplified_realization.json
1) ngen-parallel
2) ngen-serial
3) bash
#? 1
Enter the hydrofabric catchment file path: /ngen/AWI_001/config/catchments.geojson
/ngen/AWI_001/config/catchments.geojson selected
Enter the hydrofabric nexus file path: /ngen/AWI_001/config/nexus.geojson
/ngen/AWI_001/config/nexus.geojson selected
Enter the Realization file path: /ngen/AWI_001/config/awi_simplified_realization.json
/ngen/AWI_001/config/awi_simplified_realization.json selected

Your NGEN run command is ngen-parallel /ngen/AWI_001/config/catchments.geojson "" /ngen/AWI_001/config/nexus.geojson "" /ngen/AWI_001/config/awi_simplified_realization.json
Copy and paste it into the terminal to run your model.
The tested model is /dmod/bin/ngen-serial /ngen/data/catchment_data.geojson  /ngen/data/nexus_data.geojson  /ngen/ngen/data/example_realization_config.json
If your model didn't run, or encountered an error, try checking the Forcings paths in the Realizations file you selected.

Your model run is beginning!

NGen Framework 0.1.0
Missing required argument for partition file path.

## Screenshots
image

### LINKED ISSUE #25: Routing needs to be added to the latest docker image.
Currently routing is not added in the image. Need to add that.

### PR DESCRIPTION
**Pull request by hellkite500**
This image also builds/runs on arm 64 successfully, so this should allow the cross compiling of x86 and arm images.

These commits do a few things worth noting.

1. Upgrade all rocky image layers to version 9.1
2. Update the t-route build and install to use the current master branch
3. Patches ngen and the used submodules to prevent an infinite loop bug in certain I/O code.
4. Refactors the image build steps to build and run ALL tests for both serial and parallel builds.

Note that in step 4, the tests built and run will automtaically be adjusted based on the build flags/args, and if any test fails, the build will error/fail.

Closes #24 from a technical perspective, ngen parallel should work, but the realization in that issue may need to be debugged with correct library paths?
Closes #25 

Can also close #20

### CODE REVIEW

**Comment by hellkite500** [comment]
Why does fail on the PR runner 😕
```sh
HDF5_DIR=/usr pip3 install -v --install-option="\'--hdf5 \${HDF5_DIR}\'" --install-option="\'--jobs=$(nproc) \'"  --no-build-isolation tables
```
with a pip error `no such option: --install-option`

but doesn't fail locally? 🤔

**Comment by jameshalgren** [comment]
Exit Code 143 in this case is probably a resource issue: https://github.com/actions/runner-images/issues/6680

**Comment by jameshalgren** [comment]
Merging this PR is high priority. It looks like the GitHub runners are all failing -- My suspicion (I'm inexperienced) is that the 2 core 8Gb runner is getting overwhelmed. We will not have larger runners available quickly, though we should probably work on that. 

If we can confirm that this builds on several external platforms, does anyone disagree with merging the PR over the failed tests?

I'd propose that we test on these or confirm already-complete tests on the following environments, then merge the PR: 
- [ ] build on local MacOS (@jameshalgren or )
- [ ] build on AWS EC2 or GCP 2i2c (@benlee0423 or @ZacharyWills )
- [ ] build on UA local infra (BW) (@shahab122 or @benlee0423)

@hellkite500 @arpita0911patel  -- please briefly weigh in here.

**Comment by hellkite500** [comment]
I'm ok with merging for now. I built on apple arm locally and I'm working on testing an x86 cross build. Some additional validation as mentioned would be good.

**Comment by jameshalgren** [comment]
Update: On MacOS, tried the build with and without specifying the target platform. 
when building with the platform set to amd64, the error occurred in the blosc build: 
```
docker buildx build --platform=linux/amd64 -f Dockerfile -t local/dmod_ngen_test_003_amd64 .
```

image

image

**Comment by jameshalgren** [comment]
When running on MacOS without specifying the platform, the error was in the ngen build somewhere.
```
docker buildx build -f Dockerfile -t local/dmod_ngen_test_003_arm64 .
```

image

image

**Comment by benlee0423** [comment]
/test_docker_build/docker$ docker buildx build -f Dockerfile -t local/dmod_ngen_test_DOESTHISBUILDWORK .
[+] Building 0.0s (0/0)                                                                                                                                         
ERROR: invalid tag "local/dmod_ngen_test_DOESTHISBUILDWORK": repository name must be lowercase

Use the command below instead.
```
docker buildx build -f Dockerfile -t local/dmod_ngen_test_doesthisbuildwork .
```

**Comment by benlee0423** [comment]
I was able to install docker-ce on Ubuntu.
```
docker buildx build -f Dockerfile -t local/dmod_ngen_test_doesthisbuildwork .
```

Getting an error, obviously this is due to disk space. What is minimum disk space to run this build?
```
 > [rocky_build_ngen 1/8] COPY --chown= --from=rocky_init_repo /ngen/ngen /ngen/ngen:
------
Dockerfile:462
--------------------
 460 |     ARG BUILD_SLOTH
 461 |     
 462 | >>> COPY --chown=${USER} --from=rocky_init_repo ${WORKDIR}/ngen ${WORKDIR}/ngen
 463 |     COPY --chown=${USER} --from=rocky_build_troute ${WORKDIR}/t-route/wheels /tmp/t-route-wheels
 464 |     COPY --chown=${USER} --from=rocky_build_troute ${WORKDIR}/t-route/requirements.txt /tmp/t-route-requirements.txt
--------------------
ERROR: failed to solve: failed to copy files: copy file range failed: no space left on device
```

**Comment by benlee0423** [comment]
I built 4 times, and the build process got killed when it is running the below line.
I also attached entire build log and system log.
EC2 instance spec: 
OS: Ubuntu 22.04.2 LTS
RAM: 8GB
SSD: 60GB

```
#41 183.2 In file included from /ngen/ngen/include/forcing/GenericDataProvider.hpp:5,
#41 183.2                  from /ngen/ngen/include/core/catchment/HY_CatchmentRealization.hpp:7,
#41 183.2                  from /ngen/ngen/include/core/catchment/HY_CatchmentArea.hpp:4,
#41 183.2                  from /ngen/ngen/include/realizations/catchment/Catchment_Formulation.hpp:8,
#41 183.2                  from /ngen/ngen/include/realizations/catchment/Bmi_Formulation.hpp:9,
#41 183.2                  from /ngen/ngen/test/realizations/catchments/Bmi_Testing_Util.hpp:55,
#41 183.2                  from /ngen/ngen/test/realizations/catchments/Bmi_Cpp_Multi_Array_Test.cpp:6:
#41 183.2 /ngen/ngen/include/forcing/DataProviderSelectors.hpp:138:5: warning: converting ‘CSVDataSelector’ to a reference to a base class ‘CatchmentAggrDataSelector’ will never use a type conversion operator [-Wclass-conversion]
#41 183.2   138 |     operator const CatchmentAggrDataSelector&() const { return *this; }
#41 183.2       |     ^~~~~~~~
#41 183.2 /ngen/ngen/include/forcing/DataProviderSelectors.hpp:153:5: warning: converting ‘BMIDataSelector’ to a reference to a base class ‘CatchmentAggrDataSelector’ will never use a type conversion operator [-Wclass-conversion]
#41 183.2   153 |     operator const CatchmentAggrDataSelector&() const { return *this; }
#41 183.2       |     ^~~~~~~~
#41 183.2 /ngen/ngen/include/forcing/DataProviderSelectors.hpp:178:5: warning: converting ‘NetCDFDataSelector’ to a reference to a base class ‘CatchmentAggrDataSelector’ will never use a type conversion operator [-Wclass-conversion]
#41 183.2   178 |     operator const CatchmentAggrDataSelector&() const { return *this; }
#41 183.2       |     ^~~~~~~~
```
[build.log](https://github.com/AlabamaWaterInstitute/CloudInfra/files/11279414/build.log)

[i-09337d5c8429f1036.log](https://github.com/AlabamaWaterInstitute/CloudInfra/files/11279436/i-09337d5c8429f1036.log)

**Comment by hellkite500** [comment]
This is getting strange.  @benlee0423 I don't actually see an error in the build log, it just cuts off, but it looks like around the same place that @jameshalgren build was getting a `segfault` *from the compiler*.  I have been able to reproduce similar behavior on an `amd64` build on my macos, it is not always at the same place or even building the same program.  Last run I did was segfaulting `gfortran` building the fortran unit test model _after_ the ngen builds.  But I saw it fail in the ngen build a couple times as well.

I'm thinking this may be some environment setting that is hindering the compiler -- I'll keep investigating and see what I can find.

**Comment by hellkite500** [comment]
@jameshalgren on a fresh build (I had to factory reset rancher, again...) I was able to hit what looks like the same error you did, but I noticed a `segmentaiton fault` a little further up the error stack, can you look and see if you have that as well?
```
0 346.2       
#0 346.2         failed with:
#0 346.2       
#0 346.2          Segmentation fault
#0 346.2       
#0 346.2       
#0 346.2       CMake Error at /tmp/pip-build-env-f6lupk8c/overlay/lib64/python3.9/site-packages/cmake/data/share/cmake-3.26/Modules/Internal/CheckSourceCompiles.cmake:101 (try_compile):
#0 346.2         Failed to generate test project build system.
#0 346.2       Call Stack (most recent call first):
#0 346.2         /tmp/pip-build-env-f6lupk8c/overlay/lib64/python3.9/site-packages/cmake/data/share/cmake-3.26/Modules/CheckCSourceCompiles.cmake:76 (cmake_check_source_compiles)
#0 346.2         blosc2/c-blosc2/internal-complibs/zlib-ng-2.0.7/CMakeLists.txt:419 (check_c_source_compiles)
#0 346.2       
#0 346.2       
#0 346.2       -- Configuring incomplete, errors occurred!
#0 346.2       Traceback (most recent call last):
#0 346.2         File "/tmp/pip-build-env-f6lupk8c/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 666, in setup
#0 346.2           env = cmkr.configure(
#0 346.2         File "/tmp/pip-build-env-f6lupk8c/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 356, in configure
#0 346.2           raise SKBuildError(msg)
#0 346.2       
#0 346.2       An error occurred while configuring with CMake.
```

**Comment by hellkite500** [comment]
@jameshalgren on your native mac build, are how much RAM do you have allocated to your rancher vm?

**Comment by jameshalgren** [comment]
> @jameshalgren on your native mac build, are how much RAM do you have allocated to your rancher vm?

How to check? (standing by; will update if I can figure it out...)

**Comment by hellkite500** [comment]
as for the x86 issues, I was able to get an environment to test this build in, and I think I can generally reproduce the failure seen by @benlee0423.  The problem there isn't an explicit failure, but it looks to me like a potential fork bomb is eating up all the resources and just hanging/crashing the machine.  Might be related to [this issue](https://github.com/NOAA-OWP/ngen/issues/505) documented on ngen.  I'll dig into that a little more and see.

**Comment by hellkite500** [comment]
So I think I sorted this out....we asked make to do it, and make did it...from the make documentation (which is the build generator used)
```
If the ‘-j’ option is followed by an integer, this is the number of recipes to execute at once; this is called the number of job slots. If there is nothing looking like an integer after the ‘-j’ option, there is no limit on the number of job slots. 
```
and in the ngen build line, we use `-j ${BUILD_PARALLEL_JOBS}`.  But this `ARG` is never actually set, so make is is spawning up to an *unlimited* number of parallel build processes, depending on the number of possible concurrent jobs a given dependency in the build can support.  This essentially causes the system to eat up all its free memory, and all the swap, and essentially hang....

I'll push a fix momentarily that ensure `BUILD_PARALLEL_JOBS` <= nproc on the system, then I think this will succeed.

**Comment by hellkite500** [comment]
My local arm build and an AWS x86 build both successful for me now!

**Comment by benlee0423** [comment]
Docker build is successful in AWS arm64.
EC2 instance spec:
OS: Ubuntu 22.04.2 LTS
RAM: 8GB
SSD: 60GB

```
docker buildx build -f Dockerfile -t local/dmod_ngen_test_ubuntu_arm64 . &> build.log &

docker images
REPOSITORY                          TAG       IMAGE ID       CREATED          SIZE
local/dmod_ngen_test_ubuntu_arm64   latest    c5dac6248e95   32 minutes ago   3.41GB
```

Nice job @hellkite500 for getting this work.

**Review by jameshalgren — APPROVED** [review]
Works as advertised.

**Pull request merged**
